spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hidden-method:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crystalWorld?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASS}


crystal:
  remember.me.key: ${REMEMBER_ME_KEY:topsecret}

logging:
  level:
    com.example.crystalworld: DEBUG 
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      springframework:
        beans: WARN
    blog: WARN

server:
  port: 8080



